name: CI Workflow

# Körs när push till main görs
on:
  push:
    branches:

      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkar ut koden från repo
      - name: Check out code
        uses: actions/checkout@v3

      # Installerar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Installerar beroenden
      - name: Install dependencies
        run: npm install

      # Kör tester
      #- name: Run tests
      #  run: npm test -- --watchAll=false

      # Bygger applikationen
      - name: Build
        run: npm run build